### ISSUE TITLE
PHP7.2 image is not valid under "wp scaffold plugin-tests" command

### ISSUE THREAD

**Issue by shahariaazam** [wp-cli/scaffold-command#256] opened 2020-03-30 15:09 UTC
It seems that `tetraweb/php:7.2` is not a valid image anymore. So we should remove this for GitLab CI script.

```
Runtime platform      arch=amd64 os=linux pid=749 revision=4c96e5ad version=12.9.0
WARNING: You most probably have uncommitted changes. 
WARNING: These changes will not be tested.         
Running with gitlab-runner 12.9.0 (4c96e5ad)
Preparing the "docker" executor
Using Docker executor with image tetraweb/php:7.2 ...
Starting service mysql:5.6 ...
Pulling docker image mysql:5.6 ...
Using docker image sha256:c8078e8ab06d8dabd6c30cffb03951fa035d85f75c19a83ace29b01cb3ecd272 for mysql:5.6 ...
Waiting for services to be up and running...
Pulling docker image tetraweb/php:7.2 ...
ERROR: Job failed: Error response from daemon: manifest for tetraweb/php:7.2 not found: manifest unknown: manifest unknown (docker.go:196:3s)
FATAL: Error response from daemon: manifest for tetraweb/php:7.2 not found: manifest unknown: manifest unknown (docker.go:196:3s) 
```
We can also follow the similar issue related to `php7.2` on https://github.com/TetraWeb/docker/issues/60

**Comment by mvhirsch** [comment] 2022-08-27 06:22
Looks like a duplicate of #239

**Comment by swissspidy** [comment] 2023-11-10 17:18
Indeed, closing as duplicate of #239

**Closed by swissspidy** 2023-11-10 17:18 UTC
